### ISSUE TITLE
Release a version with stable 1.9.0 OpenTelemetry

### ISSUE THREAD

**Issue by alexaka1** [juliuskoval/NLog.Targets.OpenTelemetryProtocol#20]
The library depends on the beta version of otel, but 1.9.0 is stable and afaik also supports logs.
Is it possible to release a version on nuget that targets 1.9.0 as a dependency?

**Comment by juliuskoval** [comment]
Hi, OpenTelemetry logging is fully supported if you're using Microsoft's ILogger, but I need some methods and classes which are internal in stable releases, so unfortunately I need to use prerelease versions for this NLog target. See for instance here:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/451a94b2d05c90d2410de75972466ee6a30a2188/src/OpenTelemetry.Api/Logs/Logger.cs#L11-L25
